[project]
name = "mcp-korea-tourism-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachetools>=5.5.2",
    "mcp[cli]>=1.6.0",
    "ratelimit>=2.2.1",
    "tenacity>=9.1.2",
]
